### ISSUE TITLE
duckplyr

### ISSUE THREAD

**Issue by krlmlr** [davidgasquez/awesome-duckdb#121]
Where would duckplyr fit in -- "Projects" or "Integrations"? What's the difference between these two?

https://duckdblabs.github.io/duckplyr/ .

**Comment by davidgasquez** [comment]
Categories are hard! :sweat_smile: 

I'd say both might work but personally I see it more an integration than a project itself. 

Projectd are more on the end user side of things where folks rely on DuckDB for some goal like the [NBA Monte Carlo Simulation](https://github.com/matsonj/nba-monte-carlo).

**Comment by krlmlr** [comment]
Thanks for confirming. To me, "nodbi" would then also be more like an integration. Are you taking this on, do you prefer a PR?

**Comment by davidgasquez** [comment]
If you don't mind, I'd take a PR! :pray: 

You're right, `nodbi` might be a better fit for Integrations too!
