### ISSUE TITLE
Project sorting method

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/awesome-duckdb#23]
While reviewing some PRs recently I realized it could be interesting to have some guidelines around where a project should be added. For now, I'm informally keeping projects sorted chronologically by PR time.

Do you have any thoughts or suggestions @szarnyasg?

**Comment by szarnyasg** [comment]
Chronological is fine. It could also be alphabetical.
Another idea that comes to mind is sorting based on some sort of a popularity metric (e.g. GitHub stars) but that's a bit dubious, so I'd stick to chronological now.

**Comment by davidgasquez** [comment]
Thanks! Agree on keeping things chrono for now. :smile:
