### ISSUE TITLE
add DBeaver SQL IDE

### ISSUE THREAD

**Issue by bardware** [davidgasquez/awesome-duckdb#47]
I'm missing [DBeaver SQL IDE](https://duckdb.org/docs/guides/sql_editors/dbeaver.html) in the SQL Clients and IDE section.

I tried squirrelsql first, which could not handle DuckDB's JSON datatype. DBeaver can. 👍

**Comment by davidgasquez** [comment]
Indeed, DBeaver is missing! I remember looking at DuckDB support a while back and wasn't there. 

Do you mind sending a PR with it?
