### ISSUE TITLE
Add web clients

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/awesome-duckdb#51]
- https://csvfiddle.io/
- https://sekuel.com/playground/
- Others?

**Comment by davidgasquez** [comment]
Also https://sql.quacking.cloud!

**Comment by tobilg** [comment]
> Also https://sql.quacking.cloud!

It already present under https://github.com/davidgasquez/awesome-duckdb/blob/main/README.md#tools-powered-by-duckdb

**Comment by davidgasquez** [comment]
https://codapi.org/duckdb/
