### ISSUE TITLE
Including `transfermarkt-datasets`

### ISSUE THREAD

**Issue by dcaribou** [davidgasquez/awesome-duckdb#78]
Wondering if [this project](https://github.com/dcaribou/transfermarkt-datasets?tab=readme-ov-file#-data-preparation) of mine would qualify as a sample project to be included here.

The core of the pipeline is a data preparation step that runs in duckDB (it's a dbt project). I've decided to use duckDB instead of pandas for data preparation given the significant [performance improvements](https://github.com/dcaribou/transfermarkt-datasets/issues/162) it had.

If this sounds like something it would make sense let me know and I can raise a PR 😄.

**Comment by davidgasquez** [comment]
Of course! Feel free to send a PR. Is a very cool project!

**Comment by dcaribou** [comment]
PR [here](https://github.com/davidgasquez/awesome-duckdb/pull/82)!
