### ISSUE TITLE
Adding duckdb-rs? Languages section?

### ISSUE THREAD

**Issue by carlopi** [davidgasquez/awesome-duckdb#9]
I am not sure where it's the proper place, but I guess a "Languages" section could make sense, having Rust, Julia, Go, WebAssembly, (Zig?), and probably other I am forgetting.

Opening for now just an issue, will convert to PR if it seems to makes sense.

**Comment by davidgasquez** [comment]
Makes total sense! I thought it was already there in fact. Please a PR would be much appreciated.
